In [23]:
import torch
import torch.nn as nn
import torch.optim as optim

Basic autograd example 1

In [3]:
# Create tensor:
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)
print(x)
print(w)
print(b)

tensor(1., requires_grad=True)
tensor(2., requires_grad=True)
tensor(3., requires_grad=True)


In [18]:
# Build computational graph
y = w * x + b
print(y)

tensor(5., grad_fn=<AddBackward0>)


In [19]:
# Compute gradient
y.backward()
print(x.grad)
print(w.grad)
print(b.grad)

tensor(10.)
tensor(5.)
tensor(8.)


Basic autograd example 2

In [20]:
# Create tensor of shape (10, 3) and (10, 2)
x = torch.randn(10, 3)
y = torch.rand(10, 2)

In [22]:
# Build a fully connected layer
linear = nn.Linear(in_features=3, out_features=2)
print(f'w: {linear.weight}')
print(f'b: {linear.bias}')

w: Parameter containing:
tensor([[-0.2195, -0.5164, -0.0287],
        [ 0.3555, -0.0691, -0.1054]], requires_grad=True)
b: Parameter containing:
tensor([0.5108, 0.3699], requires_grad=True)


In [24]:
# Build loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.SGD(linear.parameters(), lr=0.1)

In [25]:
# Forward pass
pred = linear(x)

In [34]:
# Compute loss
loss = criterion(pred, y)
print(f'loss: {loss.item()}')

loss: 0.20708823204040527


In [36]:
# Backward pass
loss.backward()

In [38]:
# Print out gradient
print(f'dL/dw: {linear.weight.grad}')
print(f'dL/db: {linear.bias.grad}')

dL/dw: tensor([[-0.2299, -0.4125, -0.0345],
        [ 0.1180, -0.0356, -0.0875]])
dL/db: tensor([-0.0298, -0.0474])


In [39]:
# Update parameters
optimizer.step()
print(f'new w: {linear.weight}')
print(f'new b: {linear.bias}')

new w: Parameter containing:
tensor([[-0.1965, -0.4751, -0.0253],
        [ 0.3437, -0.0656, -0.0966]], requires_grad=True)
new b: Parameter containing:
tensor([0.5138, 0.3746], requires_grad=True)


In [40]:
# Compute loss after 1 gradient descent step
next_pred = linear(x)
next_loss = criterion(next_pred, y)
print(f'loss after 1 step optimization: {next_loss.item()}')

loss after 1 step optimization: 0.18327650427818298


Loading data from numpy

In [41]:
import numpy as np

In [46]:
# Create numpy array
x = np.array([[1, 2], [3, 4]])

In [47]:
# Convert numpy array to torch tensor
y = torch.from_numpy(x)
print(y)

# Making change to x result in changes in y
x[0][0] = 10
print(y)

tensor([[1, 2],
        [3, 4]])
tensor([[10,  2],
        [ 3,  4]])


In [49]:
# Convert torch tensor to numpy array
z = y.numpy()
print(type(z))

<class 'numpy.ndarray'>


Input pipeline

In [59]:
from torch.utils.data import DataLoader
import torchvision
from torchvision.transforms import ToTensor
import os

In [57]:
# Download and construct CIFAR-10
train_dataset = torchvision.datasets.CIFAR10(
    root=r'D:\pytorch_data', download=True, train=True, transform=ToTensor())


100.0%


Extracting D:\pytorch_data\cifar-10-python.tar.gz to D:\pytorch_data


In [58]:
# Fetch one data pair
image, label = train_dataset[0]
print(image.size())
print(label)

torch.Size([3, 32, 32])
6


In [60]:
# Data loader
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)

In [61]:
# load data
data_iter = iter(train_loader)

In [64]:
# mini-batch images and label
images, labels = next(data_iter)
print(len(images))
print(len(labels))

64
64


In [67]:
# Actual usage of data loader
for _, payload in enumerate(train_loader):
    images = payload[0]
    labels = payload[1]
    print(f'Mini-batch {_}: {len(images)} images, {len(labels)} labels')

Mini-batch 0: 64 images, 64 labels
Mini-batch 1: 64 images, 64 labels
Mini-batch 2: 64 images, 64 labels
Mini-batch 3: 64 images, 64 labels
Mini-batch 4: 64 images, 64 labels
Mini-batch 5: 64 images, 64 labels
Mini-batch 6: 64 images, 64 labels
Mini-batch 7: 64 images, 64 labels
Mini-batch 8: 64 images, 64 labels
Mini-batch 9: 64 images, 64 labels
Mini-batch 10: 64 images, 64 labels
Mini-batch 11: 64 images, 64 labels
Mini-batch 12: 64 images, 64 labels
Mini-batch 13: 64 images, 64 labels
Mini-batch 14: 64 images, 64 labels
Mini-batch 15: 64 images, 64 labels
Mini-batch 16: 64 images, 64 labels
Mini-batch 17: 64 images, 64 labels
Mini-batch 18: 64 images, 64 labels
Mini-batch 19: 64 images, 64 labels
Mini-batch 20: 64 images, 64 labels
Mini-batch 21: 64 images, 64 labels
Mini-batch 22: 64 images, 64 labels
Mini-batch 23: 64 images, 64 labels
Mini-batch 24: 64 images, 64 labels
Mini-batch 25: 64 images, 64 labels
Mini-batch 26: 64 images, 64 labels
Mini-batch 27: 64 images, 64 labels
Mi

Input pipeline for custom dataset

In [71]:
from torch.utils.data import Dataset, DataLoader

In [75]:
# build custom dataset
class CustomDataset(Dataset):
    def __init__(self):
        # 1. specify path of dataset
        # 2. initialize list of data file, etc.
        pass

    def __getitem__(self, idx):
        # 1. Read one data from file (using PIL, numpy, etc)
        # 2. Preprocess data
        # 3. Return data pair (image, label)
        return torch.tensor(0.), 0  # psuedo value

    def __len__(self):
        # return size of dataset
        return 1000   # psuedo value

In [76]:
# Feed custom dataset to data loader
custom_dataset = CustomDataset()
custom_loader = DataLoader(custom_dataset, batch_size=64, shuffle=True)

for _, data_pair in enumerate(custom_loader):
    pass

Pre-trained model

In [84]:
import torchvision
import torch.nn as nn
from PIL import Image

In [114]:
# Download and load the pre-trained ResNet-18
resnet = torchvision.models.resnet18(weights=torchvision.models.ResNet18_Weights)

In [117]:
# Finetune only the top layer of the model

## turn off autograd for parameter of ResNet18
for param in resnet.parameters():
    param.requires_grad = False

## replace the top layer for finetuning
resnet.fc = nn.Linear(in_features=resnet.fc.in_features, out_features=10)

In [ ]:
# Forward pass
labels = ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']

image = Image.open('./Cat03.jpg')
image = np.array(image, dtype=np.float32)
image = np.permute_dims(image, axes=(2,0,1))
image = torch.from_numpy(image)
resize = torchvision.transforms.Resize(size=224)
image = resize(image)
image = image.unsqueeze_(dim=0)
label = 'cat'
pred = labels[torch.argmax(resnet(image))]

print(pred == label)    # wrong output because new fc layer of our model is not trained

False


Save and load model

In [121]:
# save and load the entire model
torch.save(resnet, 'model.ckpt')
model = torch.load('model.ckpt')

C:\Users\admin\AppData\Local\Temp\ipykernel_1340\1556255639.py:3: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model = torch.load('model.ckpt')


In [123]:
# Save and load only model's parameters
torch.save(resnet.state_dict(), 'params.ckpt')
resnet.load_state_dict(torch.load('params.ckpt'))

C:\Users\admin\AppData\Local\Temp\ipykernel_1340\4159853325.py:3: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  resnet.load_state_dict(torch.load('params.ckpt'))


<All keys matched successfully>